name: CD - Backend Server
on:
  push:
    branches: ['main']
    paths:
      - 'backend/**'
      - '.github/workflows/publish-backend.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: onkr0d/titanic

jobs:
  build-and-push-backend:
    runs-on: ubuntu-24.04-arm   # Arm64 GitHub-hosted runner
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        target:
          - name: backend
            context: ./backend
            scope: backend
            image: backend
          - name: caddy
            context: ./backend/caddy
            scope: caddy
            image: caddy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.target.image }}

      - name: Build & push (${{ matrix.target.name }})
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.target.context }}
          platforms: linux/arm64 # we're already on arm but yeah
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.target.image }}:latest
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.target.scope }}
          cache-to: type=gha,mode=max,scope=${{ matrix.target.scope }}
          provenance: false